name: "Run sample scripts"
on:
    [push, pull_request]
jobs:
  build:
    name: Run sample scripts
    runs-on: ubuntu-latest        
    steps:
    - uses: actions/checkout@v4.1.2
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean install -DskipTests -Dproject.build.commit=${GITHUB_SHA} -Dproject.build.system=GH_ACTIONS/Maven -Dproject.build.type=CI -Dproject.repository=${{ github.server_url }}/${{ github.repository }}
    - name: Copy
      run: cp ./target/som-java-*-shaded.jar ./sample/
    - name: Rename
      run: mv sample/som-java-*-shaded.jar sample/som-java.jar
    - name: Install dos2unix
      run: sudo apt-get install -y dos2unix
    - name: Convert line endings script runner
      run: dos2unix script-runner-sample.sh
    - name: Convert line endings all sample scripts 
      run: dos2unix sample/*.sh || true
    - name: Convert line endings all sample scripts (r)
      run: dos2unix sample/**/*.sh || true
    - name: Make script runner executable
      run: chmod +x script-runner-sample.sh
    - name: Make all sample scripts executable
      run: chmod +x sample/*.sh || true
    - name: Make all sample scripts executable (r)
      run: chmod +x sample/**/*.sh || true
    - name: Run sample script runner
      run: ./script-runner-sample.sh
    - name: Clean up
      run: rm sample/som-java.jar