name: "Run sample powershell scripts on windows"
on:
  [push, pull_request]
jobs:
  build:
    name: Run sample scripts
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4.1.3
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn --% clean install -e -DskipTests -Dproject.build.commit=${GITHUB_SHA} -Dproject.build.system=GH_ACTIONS/Maven -Dproject.build.type=CI -Dproject.repository=${{ github.server_url }}/${{ github.repository }}
    - name: Copy
      run: Copy-Item -Path ./target/som-java-*-shaded.jar -Destination ./sample/
    - name: Rename
      run: Get-ChildItem -Path "./sample/" -Filter "som-java-*-shaded.jar" | Rename-Item -NewName "som-java.jar"
    - name: Convert line endings script runner
      run: (Get-Content ps-runner-sample.ps1) | Set-Content ps-runner-sample.ps1 -Encoding ASCII
    - name: Convert line endings all sample scripts
      run: Get-ChildItem sample -Recurse -Include *.ps1 | ForEach-Object { (Get-Content $_.FullName) | Set-Content $_.FullName -Encoding ASCII }
    - name: Make script runner executable
      run: Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser && Unblock-File ps-runner-test.ps1
    - name: Make all sample scripts executable
      run: Get-ChildItem sample -Recurse -Include *.ps1 | ForEach-Object { Unblock-File $_.FullName }
    - name: Run sample script runner
      run: ./ps-runner-sample.ps1
    - name: Clean up
      run: Remove-Item ./sample/som-java.jar