name: "Test"
on:
    [push, pull_request]
jobs:
  build:
    name: run_tests_all
    runs-on: ubuntu-latest        
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Test with Maven
      run: mvn clean test
